import os
import secrets
import getpass
from pathlib import Path
from typing import List, Tuple

from password_utils import (
    validate_password,
    print_password_policy,
    generate_password_suggestions,
)


def collect_files(source_dir: Path) -> List[Tuple[Path, str]]:
    if not source_dir.exists():
        raise FileNotFoundError(f"Directory not found: {source_dir}")
    if not source_dir.is_dir():
        raise ValueError(f"Path is not a directory: {source_dir}")

    files: List[Tuple[Path, str]] = []

    for abs_path in sorted(source_dir.rglob("*")):
        if abs_path.is_file():
            rel_path = abs_path.relative_to(source_dir).as_posix()
            files.append((abs_path, rel_path))

    return files


def ensure_dir(target_dir: Path) -> None:
    target_dir.mkdir(parents=True, exist_ok=True)


def safe_output_path(base_dir: Path, rel_path: str) -> Path:
    safe = (base_dir / rel_path).resolve()
    base_resolved = base_dir.resolve()

    try:
        safe.relative_to(base_resolved)
    except ValueError:
        raise ValueError(
            f"Path traversal attempt detected: {rel_path!r} escapes {base_dir}"
        )

    return safe


def random_padding(min_bytes: int = 16, max_bytes: int = 256) -> bytes:
    size = secrets.randbelow(max_bytes - min_bytes + 1) + min_bytes
    return secrets.token_bytes(size)


def prompt_password(confirm: bool = False) -> str:
    if confirm:
        print("\n[*] Password Policy:")
        print_password_policy()
        
        suggestions = generate_password_suggestions(3, 20)
        print("\n  Suggested passwords (generated by cryptographically strong RNG):")
        for i, pwd in enumerate(suggestions, 1):
            result = validate_password(pwd)
            print(f"    {i}. {pwd}  [{result.strength.value}, {result.entropy_bits:.0f} bits]")
        
        print("\n  Options:")
        print("    1-3: Use suggested password")
        print("    c:   Enter custom password")
        print()
        
        choice = input("  Your choice: ").strip().lower()
        
        if choice in ['1', '2', '3']:
            password = suggestions[int(choice) - 1]
            print(f"\n[✓] Using suggested password #{choice}")
            print(f"    Password: {password}")
            print("    ⚠️  IMPORTANT: Save this password to a secure location!")
            print("        (Password manager, encrypted notes, etc.)")
            
            save_choice = input("\n    Also save to password.txt for quick unpacking? (y/n): ").strip().lower()
            if save_choice == 'y':
                with open('password.txt', 'w') as f:
                    f.write(password)
                os.chmod('password.txt', 0o600)
                print("    ✓ Saved to password.txt")
                print("    💡 Keep this file for unpacking, delete after archive is no longer needed")
            
            input("\n    Press Enter to continue...")
            return password
        elif choice != 'c':
            raise ValueError("Invalid choice. Operation cancelled.")
    
    import sys
    if sys.platform == 'win32':
        print("\n  💡 TIP: On Windows, paste doesn't work in secure password input.")
        print("     Options:")
        print("       1. Type password manually")
        print("       2. Use --password flag: python main.py unpack archive.sarc output --password \"your_password\"")
        print("       3. Load from password.txt file (if you saved it)")
        print()
        
        load_choice = input("  Load password from password.txt? (y/n): ").strip().lower()
        if load_choice == 'y':
            try:
                with open('password.txt', 'r') as f:
                    password = f.read().strip()
                print("  ✓ Password loaded from file")
                return password
            except FileNotFoundError:
                print("  ✗ password.txt not found, please enter manually")
    
    password = getpass.getpass("Enter password: ")

    if not password:
        raise ValueError("Password cannot be empty.")

    if confirm:
        result = validate_password(password)
        print(f"\n[*] Password evaluation:\n{result}")

        if not result.is_valid:
            raise ValueError(
                "Password does not meet security requirements. "
                "Fix errors and try again."
            )

        password2 = getpass.getpass("Repeat password: ")
        if password != password2:
            raise ValueError("Passwords do not match.")

        print()

    return password


def format_size(size_bytes: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if size_bytes < 1024:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} TB"
